# Generated by Django 4.2.7 on 2023-11-28 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('birtDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('icon', models.TextField()),
                ('keyValidate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
