# Generated by Django 4.2.7 on 2023-11-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTracKids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(default='')),
                ('imagen', models.TextField(default='')),
                ('vocals', models.TextField(default='')),
                ('other', models.TextField(default='')),
                ('drums', models.TextField(default='')),
                ('bass', models.TextField(default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppTracKids.usuario')),
            ],
        ),
    ]
